name: isolate_pool
description: "An extremely user-friendly thread pool plugin."
version: 1.0.1
homepage: "https://github.com/LiuYX-Skio/isolate_pool"

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  synchronized: ^3.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  synchronized: ^3.3.0+3
