name: isolate_easy_pool
description: "An extremely user-friendly isolate pool plugin.Easy implementation of Isolate reuse and asynchronous task execution in one line of code.Automatically switching back to the main isolate function greatly improves development efficiency."
version: 0.0.8
homepage: "https://github.com/LiuYX-Skio/isolate_easy_pool"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  synchronized: ^3.3.0+3