name: isolate_easy_pool
description: "An extremely user-friendly thread pool plugin."
version: 0.0.5
homepage: "https://github.com/LiuYX-Skio/isolate_easy_pool"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  synchronized: ^3.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
