name: isolate_easy_pool
description: "An extremely user-friendly thread pool plugin."
version: 0.0.7
homepage: "https://github.com/LiuYX-Skio/isolate_easy_pool"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  synchronized: ^3.3.0+3